version: "3.7"  
services:
  ratings:
    build: ./src/ratings
    ports:
      - "8081:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
  mongodb:
    image: bitnami/mongodb:4.4.4-debian-10-r5
    volumes:
      - "./src/ratings/databases:/docker-entrypoint-initdb.d"
  details:
    build: ./src/details
    ports: 
      - "8080:8080"
  reviews:
    build: ./src/reviews
    ports: 
      - "9080:9080"
    environment:
      ENABLE_RATINGS: "true"
      RATINGS_SERVICE: "http://ratings:8080"
      STAR_COLOR: yellow
  productpage:
    build: ./src/productpage
    ports:
      - "9000:8080"
