name: Docker Image CI

on:
  push:
    branches: [ "leaning" ]

jobs:

  build-details:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file src/details/Dockerfile --tag details:latest

  build-productpage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file src/productpage/Dockerfile --tag productpage:latest

  build-ratings:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file src/ratings/Dockerfile --tag ratings:latest
      
  build-reviews:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file src/reviews/Dockerfile --tag reviews:latest
